apiVersion: v1
kind: Service
metadata:
  name: rest-client-privileged
  labels:
    app: rest-client-privileged
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: rest-client-privileged
