apiVersion: v1
kind: Service
metadata:
  name: rest-server-service
  labels:
    app: rest-server-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: rest-server-service
