apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: igw-rest-server-service
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
#    app: rest-server-service
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - istio-ingressgateway-istio-system.apps-crc.testing
#    - "*"
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rest-server-service-vs2
spec:
  hosts:
#    - "*"
    - istio-ingressgateway-istio-system.apps-crc.testing
  gateways:
    - igw-rest-server-service
  http:
  - match:
    - headers:
        client-group:
          exact: vip
    route:
      - destination:
          host: rest-server-service.rest-service-test.svc.cluster.local
          port:
            number: 8080
          subset: privileged
  - match:
      - queryParams:
          callerServiceName:
            exact: vip-client-service
    route:
      - destination:
          host: rest-server-service.rest-service-test.svc.cluster.local
          port:
            number: 8080
          subset: privileged
  - match:
    - uri:
        prefix: /reserved
    route:
      - destination:
          host: rest-server-service.rest-service-test.svc.cluster.local
          port:
            number: 8080
          subset: privileged
  - match:
    - uri:
        prefix: /getServiceResult
    route:
    - destination:
        host: rest-server-service.rest-service-test.svc.cluster.local
        port:
          number: 8080
        subset: regular
