apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: rest-service-server-gw
  namespace: rest-service-test
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*" # accept all traffic because in CRC I can only call Ingress by IP
