apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: rest-service-server-through-ingress-gateway
spec:
  host: rest-service-server.rest-service-test.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 3
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
  subsets:
  - name: privileged
    labels:
      version: v1
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 100
        http:
          http1MaxPendingRequests: 10
          maxRequestsPerConnection: 200
  - name: regular
    labels:
      version: v1
#    trafficPolicy:
#      connectionPool:
#        tcp:
#          maxConnections: 3
#        http:
#          http1MaxPendingRequests: 1
#          maxRequestsPerConnection: 1
