apiVersion: v1
kind: Service
metadata:
  name: rest-client-regular
  labels:
    app: rest-client-regular
spec:
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  selector:
    app: rest-client-regular
